---
# This playbook install space-vim

- name: install vim and provide a proper vimrc
  apt: pkg=vim state=present

- name: install awesome SpaceVim
  sudo: no
  shell: curl -sLf https://spacevim.org/install.sh | bash
