name: Sync EnvSetup in my vps

on:
  push:
    branches:
      master

env:
  SSH_ACTIONS: false
  DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
  ARGS: "-e -c -r"
  SERVER_PORT: "22"
  FOLDER: "./docs/site/public/"
  SERVER_IP: "xunqinji.top"
  USERNAME: "root"
  SERVER_DESTINATION: "/www/wwwroot/hugo/"

jobs:
  sync-EnvSetup-1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: multiple command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.OMG_HOST }}
          username: root
          key: ${{ secrets.OMG_KEY }}
          port: 22
          script: |
            cd ~/EnvSetup
            git pull
            cd /home/vagrant/EnvSetup
            git pull
            
  sync-EnvSetup-2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: multiple command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.WORLD_HOST }}
          username: root
          key: ${{ secrets.OMG_KEY }}
          port: 22
          script: |
            cd ~/EnvSetup
            git pull
