name: Sync envSetup in my vps

env:
  ROOT_NAME: root
  USER_NAME: vagrant
on:
  push:
    branches: master

jobs:
  Sync-EnvSetup-Vps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Sync setting in vps
        uses: appleboy/ssh-action@master
        with:
          host: "${{ secrets.OMG_HOST }}, ${{ secrets.WORLD_HOST}}"
          username: root
          key: ${{ secrets.OMG_KEY }}
          port: 22
          script: |
            cd /root/EnvSetup
            git pull
            cd /home/vagrant/EnvSetup
            git pull
