name: Sync EnvSetup in my vps

on:
  push:
    branches:
      master

jobs:
  sync-EnvSetup-1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: multiple command
        uses: appleboy/ssh-action@master
        with:
          host: "${{ secrets.OMG_HOST }}, ${{ secrets.WORLD_HOST}}"
          username: root
          key: ${{ secrets.OMG_KEY }}
          port: 22
          script: |
            cd ~/EnvSetup
            git pull
            cd /home/vagrant/EnvSetup
            git pull
            
